const db = require('../server/db');
const { Characters } = require('../server/db/models/characters');
const { Char_Traits } = require('../server/db/models/char_traits');
const { First_Names } = require('../server/db/models/first_names');
const { Last_Names } = require('../server/db/models/last_names');
const { Likes_Dislikes } = require('../server/db/models/likes_dislikes');
const { Motivators } = require('../server/db/models/motivators');
const { Phys_Traits } = require('../server/db/models/phys_traits');
const { Skills } = require('../server/db/models/skills');
const { Wildcards } = require('../server/db/models/wildcards');

const { Plot_Words } = require('../server/db/models/plot_words');

const characters_data = [
    {
        name: `Testy McTestPants`,
        age: 100,
        phys_descrip: `Ancient`,
        char_descrip: `Ancient-like`
    }
];

const char_traits_data = [
    { element: 'tough' },
    { element: 'strict' },
    { element: 'honest' },
    { element: 'kind' },
    { element: 'gentle' },
    { element: 'silly' },
    { element: 'abrasive' },
    { element: 'lazy' },
    { element: 'unhappy' },
    { element: 'happy' },
    { element: 'eager' },
    { element: 'friendly' },
    { element: 'talkative' },
    { element: 'shy' },
    { element: 'goofy' },
    { element: 'pure-hearted' },
    { element: 'innocent' },
    { element: 'mischievous' },
    { element: 'pot-stirring' },
    { element: 'gossipy' },
    { element: 'foul-mouthed' },
    { element: 'angry' },
    { element: 'irritable' },
    { element: 'bubbly' },
    { element: 'bouncy' },
    { element: 'sarcastic' },
    { element: 'melodramatic' },
    { element: 'organized' },
    { element: 'cruel' },
    { element: 'mysterious' },
    { element: 'groovy' },
    { element: 'spontaneous' },
    { element: 'structured' },
    { element: 'mean' },
    { element: 'grumpy' },
    { element: 'tech savvy' },
    { element: 'technologically enept' },
    { element: 'monotone' },
    { element: 'simple' },
    { element: 'dumb' },
    { element: 'intelligent' },
    { element: 'sharp' },
    { element: 'wise' },
    { element: 'easy-going' },
    { element: 'slimy' },
    { element: 'sketchy' },
    { element: 'bad-tempered' },
    { element: 'sad' },
    { element: 'reclusive' },
    { element: 'close-minded' },
    { element: 'passionate' },
    { element: 'loving' },
    { element: 'artistic' },
    { element: 'wild' },
    { element: 'respectful' },
    { element: 'astute' },
    { element: 'charismatic' },
    { element: 'observational' },
]

const first_names_data = [
      { element: 'cindy',
      gender: 'female' },
      { element: 'inola',
      gender: 'female' },
      { element: 'elise',
      gender: 'female' },
      { element: 'holly',
      gender: 'female' },
      { element: 'elodie',
      gender: 'female' },
      { element: 'sage',
      gender: 'female' },
      { element: 'yeruti',
      gender: 'female' },
      { element: 'anemone',
      gender: 'female' },
      { element: 'eleanore',
      gender: 'female' },
      { element: 'mirta',
      gender: 'female' },
      { element: 'lubanzi',
      gender: 'female' },
      { element: 'kaoru',
      gender: 'female' },
      { element: 'annie',
      gender: 'female' },
      { element: 'esha',
      gender: 'female' },
      { element: 'ren',
      gender: 'female' },
      { element: 'willow',
      gender: 'female' },
      { element: 'riko',
      gender: 'female' },
      { element: 'maureen',
      gender: 'female' },
      { element: 'navneet',
      gender: 'female' },
      { element: 'nanami',
      gender: 'female' },
      { element: 'lila',
      gender: 'female' },
      { element: 'amora',
      gender: 'female' },
      { element: 'topsy',
      gender: 'female' },
      { element: 'roosa',
      gender: 'female' },
      { element: 'setsuko',
      gender: 'female' },
      { element: 'clara',
      gender: 'female' },
      { element: 'delilah',
      gender: 'female' },
      { element: 'constanza',
      gender: 'female' },
      { element: 'tawny',
      gender: 'female' },
      { element: 'zola',
      gender: 'female' },
      { element: 'chanah',
      gender: 'female' },
      { element: 'chae-won',
      gender: 'female' },
      { element: 'sharla',
      gender: 'female' },
      { element: 'franny',
      gender: 'female' },
      { element: 'anupama',
      gender: 'female' },
      { element: 'maleah',
      gender: 'female' },
      { element: 'julienne',
      gender: 'female' },
      { element: 'lorenza',
      gender: 'female' },
      { element: 'chetana',
      gender: 'female' },

      { element: 'howie',
      gender: 'male' },
      { element: 'george',
      gender: 'male' },
      { element: 'hidemi',
      gender: 'male' },
      { element: 'raj',
      gender: 'male' },
      { element: 'lucas',
      gender: 'male' },
      { element: 'murugan',
      gender: 'male' },
      { element: 'wu',
      gender: 'male' },
      { element: 'grier',
      gender: 'male' },
      { element: 'clemente',
      gender: 'male' },
      { element: 'viraj',
      gender: 'male' },
      { element: 'francis',
      gender: 'male' },
      { element: 'wendelin',
      gender: 'male' },
      { element: 'nassim',
      gender: 'male' },
      { element: 'myeong',
      gender: 'male' },
      { element: 'knute',
      gender: 'male' },
      { element: 'haruto',
      gender: 'male' },
      { element: 'horacio',
      gender: 'male' },
      { element: 'emilio',
      gender: 'male' },
      { element: 'octavio',
      gender: 'male' },
      { element: 'jae',
      gender: 'male' },
      { element: 'inderjit',
      gender: 'male' },
      { element: 'abraham',
      gender: 'male' },
      { element: 'azhar',
      gender: 'male' },
      { element: 'spike',
      gender: 'male' },
      { element: 'brady',
      gender: 'male' },
      { element: 'kiyoshi',
      gender: 'male' },
      { element: 'heraclio',
      gender: 'male' },
      { element: 'darrian',
      gender: 'male' },
      { element: 'kev',
      gender: 'male' },
      { element: 'blas',
      gender: 'male' },
      { element: 'ashton',
      gender: 'male' },
      { element: 'seok-jin',
      gender: 'male' },
      { element: 'shiv',
      gender: 'male' },
      { element: 'seymour',
      gender: 'male' },
      { element: 'ahsan',
      gender: 'male' },
      { element: 'evaristo',
      gender: 'male' },
      { element: 'alistair',
      gender: 'male' },
      { element: 'onni',
      gender: 'male' },
      { element: 'yuki',
      gender: 'male' },
      { element: 'rishi',
      gender: 'male' },
      { element: 'katashi',
      gender: 'male' },
      { element: 'cruz',
      gender: 'male' },
      { element: 'ronnie',
      gender: 'male' },
      { element: 'hai',
      gender: 'male' },
      { element: 'devyn',
      gender: 'male' },
      { element: 'akito',
      gender: 'male' },
      { element: 'khaled',
      gender: 'male' },

      { element: 'pip',
      gender: 'unisex' },
      { element: 'chikondi',
      gender: 'unisex' },
      { element: 'alexis',
      gender: 'unisex' },
      { element: 'padraigin',
      gender: 'unisex' },
      { element: 'chidubem',
      gender: 'unisex' },
      { element: 'zhong',
      gender: 'unisex' },
      { element: 'ling',
      gender: 'unisex' },
      { element: 'motya',
      gender: 'unisex' },
      { element: 'shiori',
      gender: 'unisex' },
      { element: 'arlie',
      gender: 'unisex' },
      { element: 'windsor',
      gender: 'unisex' },
      { element: 'jas',
      gender: 'unisex' },
      { element: 'raven',
      gender: 'unisex' },
      { element: 'rowen',
      gender: 'unisex' },
      { element: 'simran',
      gender: 'unisex' },
      { element: 'sky',
      gender: 'unisex' },
      { element: 'iseul',
      gender: 'unisex' },
      { element: 'presley',
      gender: 'unisex' },
      { element: 'marley',
      gender: 'unisex' },
      { element: 'neely',
      gender: 'unisex' },
      { element: 'rene',
      gender: 'unisex' },
      { element: 'jamie',
      gender: 'unisex' },
      { element: 'salem',
      gender: 'unisex' },
      { element: 'harley',
      gender: 'unisex' },
]

const last_names_data = [
    { element: 'lauper' },
    { element: 'gao' },
    { element: 'keith' },
    { element: 'knowles' },
    { element: 'sharma' },
    { element: 'li' },
    { element: 'knox' },
    { element: 'blanc' },
    { element: 'patil' },
    { element: 'blum' },
    { element: 'boatwright' },
    { element: 'blythe' },
    { element: 'borgia' },
    { element: 'joshi' },
    { element: 'borja' },
    { element: 'boulos' },
    { element: 'singh' },
    { element: 'boyd' },
    { element: 'wang' },
    { element: 'challa' },
    { element: 'marinos' },
    { element: 'markusson' },
    { element: 'masi' },
    { element: 'mason' },
    { element: 'kaur' },
    { element: 'mcafee' },
    { element: 'medina' },
    { element: 'meyer' },
    { element: 'xu' },
    { element: 'yamada' },
    { element: 'yang' },
    { element: 'young' },
    { element: 'zaman' },
    { element: 'grigorov' },
    { element: 'guevara' },
    { element: 'ahmed' },
    { element: 'hagihara' },
    { element: 'haraldsson' },
    { element: 'hashemi' },
    { element: 'devos' },
    { element: 'doran' },
    { element: 'dong' },
    { element: 'dubois' },
    { element: 'dyson' },
    { element: 'gujarati' },
]

const likes_dislikes_data = [
    { element: 'exercise' },
    { element: 'friendship' },
    { element: 'dogs' },
    { element: 'cats' },
    { element: 'storms' },
    { element: 'long car rides' },
    { element: 'reading' },
    { element: 'puzzles' },
    { element: 'murder mysteries' },
    { element: 'scary movies' },
    { element: 'rats' },
    { element: 'the woods' },
    { element: 'the beach' },
    { element: 'mischief' },
    { element: 'chaos' },
    { element: 'arguments' },
    { element: 'fights' },
    { element: 'worship' },
    { element: 'peace' },
    { element: 'the outdoors' },
    { element: 'the indoors' },
    { element: 'big cities' },
    { element: 'animals' },
    { element: 'volunteer work' },
    { element: 'giving to charity' },
    { element: 'big parties' },
    { element: 'talking to people' },
    { element: 'group conversations' },
    { element: 'being alone' },
    { element: 'the dark' },
    { element: 'spiders' },
    { element: 'hard work' },
    { element: 'older people' },
    { element: 'babies' },
    { element: 'rich people' },
    { element: 'money' },
    { element: 'eating at restaurants' },
    { element: 'their job' },
    { element: 'their partner' },
    { element: 'their best friend' },
    { element: 'their mother' },
    { element: 'their father' },
    { element: 'jewelry' },
    { element: 'sleeping' },
    { element: 'their sibling' },
    { element: 'fantasy books' },
    { element: 'sci-fi movies' },
    { element: 'true crime podcasts' },
    { element: 'fireworks' },
    { element: 'parades' },
    { element: 'christmas' },
    { element: 'shopping' },
    { element: 'the holidays' },
    { element: 'school' },
    { element: 'their town' },
    { element: 'the government' },
    { element: 'humor' },
]

const motivators_data = [
    { element: 'physical fitness' },
    { element: 'vengeance' },
    { element: 'competition' },
    { element: 'money' },
    { element: 'status' },
    { element: 'happiness' },
    { element: 'family' },
    { element: 'friendship' },
    { element: 'the pursuit of knowledge' },
    { element: 'wisdom' },
    { element: 'survival' },
    { element: 'hunger' },
    { element: 'conservation' },
    { element: 'justice' },
    { element: 'disruption' },
    { element: 'pranks' },
    { element: 'evil' },
    { element: 'progress' },
    { element: 'a rivalry' },
    { element: 'spirituality' },
    { element: 'public opinion' },
    { element: 'illness' },
    { element: 'insanity' },
]

const phys_traits_data = [
    { element: 'big-haired',
      gender: 'unisex' },
      { element: 'tall',
      gender: 'unisex' },
      { element: 'short',
      gender: 'unisex' },
      { element: 'lanky',
      gender: 'unisex' },
      { element: 'round',
      gender: 'unisex' },
      { element: 'small',
      gender: 'unisex' },
      { element: 'large',
      gender: 'unisex' },
      { element: 'disheveled',
      gender: 'unisex' },
      { element: 'prim',
      gender: 'unisex' },
      { element: 'well-dressed',
      gender: 'unisex' },
      { element: 'messy-haired',
      gender: 'unisex' },
      { element: 'short-haired',
      gender: 'unisex' },
      { element: 'pink-haired',
      gender: 'unisex' },
      { element: 'gray-haired',
      gender: 'unisex' },
      { element: 'broad-shouldered',
      gender: 'unisex' },
      { element: 'square-jawed',
      gender: 'unisex' },
      { element: 'portly',
      gender: 'unisex' },
      { element: 'lean',
      gender: 'unisex' },
      { element: 'sickly-looking',
      gender: 'unisex' },
      { element: 'hunched',
      gender: 'unisex' },
      { element: 'shaggy',
      gender: 'unisex' },
      { element: 'rat-like',
      gender: 'unisex' },
      { element: 'spindley',
      gender: 'unisex' },
      { element: 'flat-footed',
      gender: 'unisex' },
      { element: 'barrel-chested',
      gender: 'unisex' },
      { element: 'big-nosed',
      gender: 'unisex' },
      { element: 'top heavy',
      gender: 'unisex' },
      { element: 'snub-nosed',
      gender: 'unisex' },
      { element: 'small-headed',
      gender: 'unisex' },
      { element: 'doe-eyed',
      gender: 'unisex' },
      { element: 'almond-eyed',
      gender: 'unisex' },
      { element: 'hairy',
      gender: 'unisex' },
      { element: 'rotund',
      gender: 'unisex' },
      { element: 'pear-shaped',
      gender: 'unisex' },
      { element: 'freckled',
      gender: 'unisex' },
      { element: 'clean-shaven',
      gender: 'male' },
      { element: 'scruffy',
      gender: 'male' },
      { element: 'delicate-fingered',
      gender: 'unisex' },
      { element: 'dainty',
      gender: 'unisex' },
      { element: 'light on their feet',
      gender: 'unisex' },
      { element: 'trout-mouthed',
      gender: 'unisex' },
      { element: 'plump-cheeked',
      gender: 'unisex' },
      { element: 'smooth-skinned',
      gender: 'unisex' },
      { element: 'dewy',
      gender: 'unisex' },
      { element: 'greasy',
      gender: 'unisex' },
      { element: 'bespectacled',
      gender: 'unisex' },
]

const skills_data = [
    { element: 'inspiring others' },
    { element: 'sports' },
    { element: 'telling jokes' },
    { element: 'singing' },
    { element: 'making conversation' },
    { element: 'taking care of others' },
    { element: 'listening' },
    { element: 'feats of strength' },
    { element: 'acrobatics' },
    { element: 'swimming' },
    { element: 'poker' },
    { element: 'fishing' },
    { element: 'hunting' },
    { element: 'cooking' },
    { element: 'identifying smells' },
    { element: 'sowing seeds of chaos' },
    { element: 'farming' },
    { element: 'driving' },
    { element: 'running' },
    { element: 'decorating' },
    { element: 'organization' },
    { element: 'managing others' },
    { element: 'drawing' },
    { element: 'writing' },
    { element: 'art' },
    { element: 'fighting' },
    { element: 'computer work' },
    { element: 'birding' },
    { element: 'dancing' },
]

const wildcards_data = [
    { element: 'are vegetarian' },
    { element: 'have no social media' },
    { element: 'have been kidnapped' },
    { element: 'have committed murder' },
    { element: 'have witnessed murder' },
    { element: 'investigate crime' },
    { element: 'prefer dressing up' },
    { element: 'just had a makeover' },
    { element: 'have never watched television' },
    { element: 'cannot tie their shoelaces' },
    { element: 'smoke' },
    { element: 'climb trees' },
    { element: 'come from a far away place' },
    { element: 'relate to nobody in their life' },
    { element: 'regularly participate in protests' },
    { element: 'never graduated high school' },
    { element: 'peaked in high school' },
    { element: 'have the entire dictionary memorized' },
    { element: 'are afraid of the outdoors' },
    { element: 'practice witchcraft' },
    { element: 'have seven pet cats' },
    { element: 'religiously make their own bread' },
    { element: 'are a part-time cowboy' },
    { element: 'like setting things on fire' },
    { element: 'walk with a limp' },
    { element: 'have an extra finger' },
    { element: 'had a speech impediment' },
    { element: 'enjoy LARPing' },
    { element: 'are allergic to broccoli' },
    { element: 'have no sense of smell' },
    { element: 'have no sense of taste' },
    { element: 'are in a gang' },
    { element: 'have a powerful and sinister family' },
    { element: 'have a dangerous family secret' },
    { element: 'are in major debt' },
    { element: 'live a life of crime' },
    { element: 'committed a heroic act' },
    { element: 'made a huge sacrifice in their younger days' },
    { element: 'have a missing sister' },
    { element: 'are a sports champion' },
    { element: 'are thinking of running away' },
]



const plot_words_data = [
    { element: 'ship' },
    { element: 'museum' },
    { element: 'frat bro' },
    { element: 'a mistake' },
    { element: 'fireworks' },
    { element: 'attack' },
    { element: 'fish' },
    { element: 'air horn' },
    { element: 'jeans' },
    { element: 'crash' },
    { element: 'child' },
    { element: 'ear' },
    { element: 'worm' },
    { element: 'parasite' },
    { element: 'boulder' },
    { element: 'pirate' },
    { element: 'agitation' },
    { element: 'map' },
    { element: 'ski mask' },
    { element: 'spirit' },
    { element: 'tour guide' },
    { element: 'vampire' },
    { element: 'pickup truck' },
    { element: 'alabama' },
    { element: 'beach house' },
    { element: 'vulture' },
    { element: 'alien' },
    { element: 'bloom' },
    { element: 'jungle' },
    { element: 'carpenter' },
    { element: 'elevator' },
    { element: 'chihuahua' },
    { element: 'blood' },
    { element: 'booger' },
    { element: 'egg' },
]



async function seed() {
    await db.sync({ force: true });
    console.log('db synced!');

    for (character of characters_data) {
        await Characters.create(character);
    }
    for (trait of char_traits_data) {
        await Char_Traits.create(trait);
    }
    for (first_name of first_names_data) {
        await First_Names.create(first_name);
    }
    for (last_name of last_names_data) {
        await Last_Names.create(last_name);
    }
    for (like_dislike of likes_dislikes_data) {
        await Likes_Dislikes.create(like_dislike);
    }
    for (motivator of motivators_data) {
        await Motivators.create(motivator);
    }
    for (phys_trait of phys_traits_data) {
        await Phys_Traits.create(phys_trait);
    }
    for (skill of skills_data) {
        await Skills.create(skill);
    }
    for (wildcard of wildcards_data) {
        await Wildcards.create(wildcard);
    }

    for (word of plot_words_data) {
        await Plot_Words.create(word);
    }
}

async function runSeed() {
    console.log('seeding...');

    try {
        await seed();
    } catch (err) {
        console.log(err);
        process.exitCode = 1;
    } finally {
        console.log('closing db connection');
        await db.close();

        console.log('db connection closed');
    }
}

if (module == require.main) {
    runSeed();
}